module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        ember: {
          sidebar: "#0B5D3D",
          "sidebar-hover": "#094A35",
          surface: "#0B5D3D",
          "surface-muted": "#073628",
          primary: "#3DA660",
          "primary-hover": "#2D8B5E",
          accent: "#8CC63F",
          "light-lime": "#D4E8A8",
          card: "#F8FBFA",
          border: "#E0E8E4",
          text: "#1F1F1F",
          "text-secondary": "#555555",
          success: "#2FA377",
          warning: "#F5A623",
          error: "#DC3545",
          info: "#0099CC",
          disabled: "#CCCCCC",
          "chat-dark": "#1E2E26",
          "chat-bubble-mid": "#073628",
          "gradient-mid": "#052A1C",
        },
        brand: {
          primary: "#7DC600",
          secondary: "#F59E0B",
          dark: "#0B5D3D",
          light: "#14714B",
          accent: "#A3D42A",
          hover: "#5DAF10",
        },
        app: {
          bg: "#F8FBFA",
          sidebar: "#EAF6ED",
          card: "#FFFFFF",
          panel: "#F1F9F3",
          elevated: "#E3F3E8",
          border: "#D7E9DC",
          "active-bg": "rgba(125,198,0,0.16)",
        },
        status: {
          green: "#7DC600",
          orange: "#F59E0B",
          red: "#E74C3C",
          blue: "#3498DB",
          cyan: "#29B6F6",
          "light-red": "#FF6B6B",
          "light-green": "#A3D42A",
        },
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        body:    ["DM Sans", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
      },
      backgroundImage: {
        "hero-gradient":     "radial-gradient(ellipse at 60% 0%, #EAF7EE 0%, #F8FBFA 45%, #FFFFFF 100%)",
        "card-gradient":     "linear-gradient(135deg, #F1F9F3 0%, #EAF6ED 100%)",
        "glow-green":        "radial-gradient(ellipse at center, rgba(125,198,0,0.16) 0%, transparent 70%)",
        "satellite-grid":    "linear-gradient(rgba(11,93,61,0.08) 1px, transparent 1px), linear-gradient(90deg, rgba(11,93,61,0.08) 1px, transparent 1px)",
        "cta-gradient":      "linear-gradient(135deg, #0B5D3D 0%, #14714B 50%, #1E9B63 100%)",
        "btn-primary-grad":  "linear-gradient(135deg, #7DC600 0%, #5DAF10 100%)",
      },
      boxShadow: {
        "glow-sm":    "0 0 12px rgba(125,198,0,0.18)",
        "glow-md":    "0 0 24px rgba(125,198,0,0.22)",
        "glow-lg":    "0 0 48px rgba(125,198,0,0.16)",
        "card-dark":  "0 8px 24px rgba(11,93,61,0.10)",
        "card-hover": "0 16px 40px rgba(125,198,0,0.18)",
        "navbar":     "0 1px 24px rgba(11,93,61,0.08)",
      },
      animation: {
        "satellite-orbit": "satellite-orbit 20s linear infinite",
        "pulse-green":     "pulse-green 2s ease-in-out infinite",
        "scan-line":       "scan-line 3s ease-in-out infinite",
        float:             "float 6s ease-in-out infinite",
        ticker:            "ticker 30s linear infinite",
        marquee:           "marquee 22s linear infinite",
        "fade-up":         "fade-up 0.6s ease both",
        "fade-in":         "fade-in 0.5s ease both",
        "scale-in":        "scale-in 0.5s ease both",
        shimmer:           "shimmer 2.5s linear infinite",
        "spin-slow":       "spin 8s linear infinite",
      },
      keyframes: {
        "satellite-orbit": {
          "0%":   { transform: "rotate(0deg) translateX(200px) rotate(0deg)" },
          "100%": { transform: "rotate(360deg) translateX(200px) rotate(-360deg)" },
        },
        "pulse-green": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(125,198,0,0.4)" },
          "50%":       { boxShadow: "0 0 0 12px rgba(125,198,0,0)" },
        },
        "scan-line": {
          "0%":   { top: "0%", opacity: "0.8" },
          "50%":  { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":       { transform: "translateY(-12px)" },
        },
        ticker: {
          "0%":   { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        marquee: {
          "0%":   { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to:   { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%":   { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
};
